{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/glovounifieddesignsystem"]},{"paths":["\/documentation\/glovounifieddesignsystem"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ThemeManager"],"title":"Classes"},{"identifiers":["doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/BadgeDisplayingProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/BlobIconSizingProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/BlobIconTypeProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ColorSchemeProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreColorSchemeProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreFoundationUnitsProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreTextStylesProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/FoundationUnitsProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IconSizingProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Illustration","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IllustrationBlob","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IllustrationBlobType","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXOLogger","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TextStylesProtocol","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ThemeProtocol"],"title":"Protocols"},{"identifiers":["doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob01","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob02","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob03","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob04","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob05","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob06","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ClickableIcon","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreBorderWidth","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreColorScheme","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreCornerRadius","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreFoundationUnits","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreSpacer","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreTextStyles","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalBlobIcon","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalButtonStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalIllustrationBlob","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalSecondaryTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/EmptyStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/FloatingButtonStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/FloatingIllustrationBlob","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputFooter","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputHeader","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/KeyboardConfiguration","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/LoyaltyBlobIcon","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/LoyaltySecondaryTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/LoyaltyTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingBlobIcon","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingIllustrationBlob","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingSecondaryTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralBlobIcon","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralButtonStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralIllustrationBlob","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralSecondaryTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXOLogEvent","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveBlobIcon","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveIllustrationBlob","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveSecondaryTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PrimaryButtonStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionBlobIcon","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionIllustrationBlob","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionSecondaryTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/SecondaryButtonStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow01","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow02","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow03","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow04","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow05","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ShapeDecorator","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TextStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Theme","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TransparentButtonStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/WarningSecondaryTagStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/WarningTagStyle"],"title":"Structures"},{"identifiers":["doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ButtonStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreTheme"],"title":"Type Aliases"},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ControlAlignment","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/HelperTextStyle","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IconAsset","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IllustrationSize","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputSize","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputState","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Primitives","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/UDS"]},{"identifiers":["doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Foundation","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Swift","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/SwiftUI","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/UIKit"],"title":"Extended Modules"}],"kind":"symbol","metadata":{"role":"collection","roleHeading":"Framework","externalID":"GlovoUnifiedDesignSystem","title":"GlovoUnifiedDesignSystem","modules":[{"name":"GlovoUnifiedDesignSystem"}],"symbolKind":"module"},"references":{"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/InputSize":{"kind":"symbol","url":"\/documentation\/glovounifieddesignsystem\/inputsize","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InputSize"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputSize","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InputSize"}],"title":"InputSize"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Swift":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"Swift","url":"\/documentation\/glovounifieddesignsystem\/swift","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Swift"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/FloatingButtonStyle":{"abstract":[{"text":"For buttons that are set against a saturated background","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/FloatingButtonStyle","title":"FloatingButtonStyle","url":"\/documentation\/glovounifieddesignsystem\/floatingbuttonstyle","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingButtonStyle"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingButtonStyle"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/MarketingTagStyle":{"url":"\/documentation\/glovounifieddesignsystem\/marketingtagstyle","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketingTagStyle"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingTagStyle","type":"topic","abstract":[{"text":"A TagStyle concrete type for representing ","type":"text"},{"type":"codeVoice","code":"Marketing"},{"type":"text","text":" tag style"}],"role":"symbol","navigatorTitle":[{"text":"MarketingTagStyle","kind":"identifier"}],"title":"MarketingTagStyle"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreFoundationUnitsProtocol":{"url":"\/documentation\/glovounifieddesignsystem\/corefoundationunitsprotocol","kind":"symbol","type":"topic","title":"CoreFoundationUnitsProtocol","role":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreFoundationUnitsProtocol","navigatorTitle":[{"text":"CoreFoundationUnitsProtocol","kind":"identifier"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFoundationUnitsProtocol","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreTextStyles":{"abstract":[],"navigatorTitle":[{"text":"CoreTextStyles","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreTextStyles","title":"CoreTextStyles","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoreTextStyles"}],"url":"\/documentation\/glovounifieddesignsystem\/coretextstyles"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreFoundationUnits":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoreFoundationUnits"}],"kind":"symbol","title":"CoreFoundationUnits","navigatorTitle":[{"text":"CoreFoundationUnits","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreFoundationUnits","url":"\/documentation\/glovounifieddesignsystem\/corefoundationunits","role":"symbol","type":"topic","abstract":[]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PTXOLogEvent":{"abstract":[{"type":"text","text":"A value that describes a log event."}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXOLogEvent","navigatorTitle":[{"text":"PTXOLogEvent","kind":"identifier"}],"title":"PTXOLogEvent","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PTXOLogEvent","kind":"identifier"}],"role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/ptxologevent","kind":"symbol","type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/BlobIconSizingProtocol":{"navigatorTitle":[{"kind":"identifier","text":"BlobIconSizingProtocol"}],"title":"BlobIconSizingProtocol","abstract":[{"type":"text","text":"A protocol used to define a functionality for setting size for SwiftUI’s Image and UIKit’s UIImage"}],"type":"topic","role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/blobiconsizingprotocol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/BlobIconSizingProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"BlobIconSizingProtocol","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/KeyboardConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"KeyboardConfiguration"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/KeyboardConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardConfiguration"}],"url":"\/documentation\/glovounifieddesignsystem\/keyboardconfiguration","abstract":[],"role":"symbol","title":"KeyboardConfiguration","type":"topic","kind":"symbol"},"https://www.figma.com/file/TuxClC4JIItgCYAZiafQBt/Unified-Design-System?node-id=17854%3A102215&mode=dev":{"type":"link","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?node-id=17854%3A102215&mode=dev","url":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?node-id=17854%3A102215&mode=dev","titleInlineContent":[{"text":"Figma Link","type":"text"}],"title":"Figma Link"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Primitives":{"url":"\/documentation\/glovounifieddesignsystem\/primitives","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Primitives","kind":"identifier"}],"title":"Primitives","abstract":[],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Primitives","navigatorTitle":[{"kind":"identifier","text":"Primitives"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PrimaryButtonStyle":{"abstract":[{"text":"Reserved for the main action. Maximum 1 per screen.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PrimaryButtonStyle","title":"PrimaryButtonStyle","url":"\/documentation\/glovounifieddesignsystem\/primarybuttonstyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PrimaryButtonStyle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PrimaryButtonStyle","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreCornerRadius":{"type":"topic","title":"CoreCornerRadius","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreCornerRadius","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CoreCornerRadius","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreCornerRadius","url":"\/documentation\/glovounifieddesignsystem\/corecornerradius","abstract":[{"text":"A struct that a group of different configuration values for corner radius ","type":"text"},{"isActive":true,"identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=13396%3A2810&mode=design&t=6FaBdJ3Fh3yPpMNO-1","type":"reference"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/LoyaltyTagStyle":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/LoyaltyTagStyle","title":"LoyaltyTagStyle","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Loyalty"},{"text":" tag style","type":"text"}],"url":"\/documentation\/glovounifieddesignsystem\/loyaltytagstyle","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoyaltyTagStyle"}],"navigatorTitle":[{"text":"LoyaltyTagStyle","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/TagStyle":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagStyle"}],"navigatorTitle":[{"text":"TagStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the required properties to set the style for the "},{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/Tag","isActive":true,"type":"reference"},{"text":" component.","type":"text"}],"title":"TagStyle","role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/tagstyle","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TagStyle"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CriticalTagStyle":{"url":"\/documentation\/glovounifieddesignsystem\/criticaltagstyle","title":"CriticalTagStyle","role":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalTagStyle","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Critical"},{"type":"text","text":" tag style"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"CriticalTagStyle","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CriticalTagStyle","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PositiveSecondaryTagStyle":{"kind":"symbol","url":"\/documentation\/glovounifieddesignsystem\/positivesecondarytagstyle","title":"PositiveSecondaryTagStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PositiveSecondaryTagStyle","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveSecondaryTagStyle","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Positive Secondary"},{"text":" tag style","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PositiveSecondaryTagStyle"}]},"https://www.figma.com/file/TuxClC4JIItgCYAZiafQBt/Unified-Design-System?type=design&node-id=17859-132336&mode=design&t=8XdUJNM2N0s1PV77-0":{"url":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=17859-132336&mode=design&t=8XdUJNM2N0s1PV77-0","title":"Figma Link","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=17859-132336&mode=design&t=8XdUJNM2N0s1PV77-0","type":"link","titleInlineContent":[{"type":"text","text":"Figma Link"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/NeutralSecondaryTagStyle":{"title":"NeutralSecondaryTagStyle","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeutralSecondaryTagStyle"}],"kind":"symbol","navigatorTitle":[{"text":"NeutralSecondaryTagStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralSecondaryTagStyle","type":"topic","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Neutral Secondary"},{"type":"text","text":" tag style"}],"url":"\/documentation\/glovounifieddesignsystem\/neutralsecondarytagstyle"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreColorScheme":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreColorScheme","abstract":[{"type":"text","text":"A concrete type that implement "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreColorSchemeProtocol"},{"type":"text","text":" and uses its default implementation"}],"url":"\/documentation\/glovounifieddesignsystem\/corecolorscheme","title":"CoreColorScheme","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoreColorScheme"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreColorScheme"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Shadow03":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow03","url":"\/documentation\/glovounifieddesignsystem\/shadow03","navigatorTitle":[{"text":"Shadow03","kind":"identifier"}],"type":"topic","title":"Shadow03","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Shadow03"}],"abstract":[{"type":"text","text":"A Shadow shape for varient 3, to be used in SwiftUI"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/FloatingIllustrationBlob":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/FloatingIllustrationBlob","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingIllustrationBlob","kind":"identifier"}],"abstract":[],"title":"FloatingIllustrationBlob","navigatorTitle":[{"kind":"identifier","text":"FloatingIllustrationBlob"}],"type":"topic","url":"\/documentation\/glovounifieddesignsystem\/floatingillustrationblob"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/ShapeDecorator":{"title":"ShapeDecorator","abstract":[],"url":"\/documentation\/glovounifieddesignsystem\/shapedecorator","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ShapeDecorator","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ShapeDecorator","kind":"identifier"}],"navigatorTitle":[{"text":"ShapeDecorator","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/IconSizingProtocol":{"navigatorTitle":[{"text":"IconSizingProtocol","kind":"identifier"}],"type":"topic","role":"symbol","title":"IconSizingProtocol","url":"\/documentation\/glovounifieddesignsystem\/iconsizingprotocol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IconSizingProtocol","kind":"symbol","abstract":[{"type":"text","text":"A protocol used to define a functionality for setting size for SwiftUI’s Image and UIKit’s UIImage"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IconSizingProtocol","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Illustration":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Illustration","title":"Illustration","abstract":[{"text":"The PTXO Illustration","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=17859-132336&mode=design&t=8XdUJNM2N0s1PV77-0","isActive":true}],"url":"\/documentation\/glovounifieddesignsystem\/illustration","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Illustration","kind":"identifier"}],"navigatorTitle":[{"text":"Illustration","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Blob04":{"url":"\/documentation\/glovounifieddesignsystem\/blob04","abstract":[{"type":"text","text":"A Blob shape for varient 4, to be used in SwiftUI"}],"kind":"symbol","navigatorTitle":[{"text":"Blob04","kind":"identifier"}],"title":"Blob04","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Blob04"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob04"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Shadow02":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow02","abstract":[{"text":"A Shadow shape for varient 2, to be used in SwiftUI","type":"text"}],"url":"\/documentation\/glovounifieddesignsystem\/shadow02","title":"Shadow02","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Shadow02"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Shadow02"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PTXO":{"url":"\/documentation\/glovounifieddesignsystem\/ptxo","kind":"symbol","abstract":[{"type":"text","text":"A name space the will act as an umbrella for all the PTXO Atoms"}],"title":"PTXO","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PTXO","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PTXO"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PromotionTagStyle":{"abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"code":"Promotion","type":"codeVoice"},{"text":" tag style","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionTagStyle","type":"topic","url":"\/documentation\/glovounifieddesignsystem\/promotiontagstyle","title":"PromotionTagStyle","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PromotionTagStyle"}],"navigatorTitle":[{"kind":"identifier","text":"PromotionTagStyle"}],"role":"symbol"},"https://www.figma.com/file/TuxClC4JIItgCYAZiafQBt/Unified-Design-System?type=design&node-id=6158%3A53887&mode=design&t=6FaBdJ3Fh3yPpMNO-1":{"type":"link","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=6158%3A53887&mode=design&t=6FaBdJ3Fh3yPpMNO-1","url":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=6158%3A53887&mode=design&t=6FaBdJ3Fh3yPpMNO-1","titleInlineContent":[{"text":"Figma Link","type":"text"}],"title":"Figma Link"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PromotionIllustrationBlob":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionIllustrationBlob","abstract":[],"title":"PromotionIllustrationBlob","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PromotionIllustrationBlob"}],"url":"\/documentation\/glovounifieddesignsystem\/promotionillustrationblob","type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PromotionIllustrationBlob"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PTXO/BlobIcon":{"navigatorTitle":[{"text":"BlobIcon","kind":"identifier"}],"title":"PTXO.BlobIcon","abstract":[{"type":"text","text":"Unified Design System  BlobIcon."},{"text":" ","type":"text"},{"identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=9037%3A84272&mode=design&t=wYrUd7S2B73HiIJ9-1","type":"reference","isActive":true}],"type":"topic","role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/ptxo\/blobicon","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlobIcon"}],"kind":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PositiveIllustrationBlob":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveIllustrationBlob","abstract":[],"title":"PositiveIllustrationBlob","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PositiveIllustrationBlob"}],"url":"\/documentation\/glovounifieddesignsystem\/positiveillustrationblob","type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PositiveIllustrationBlob"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/InputHeader":{"kind":"symbol","title":"InputHeader","navigatorTitle":[{"kind":"identifier","text":"InputHeader"}],"url":"\/documentation\/glovounifieddesignsystem\/inputheader","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputHeader","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InputHeader","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Theme":{"title":"Theme","abstract":[{"text":"a Struct that groups sets of colors, text styles, and units, which are the fundamental of the theme","type":"text"}],"kind":"symbol","url":"\/documentation\/glovounifieddesignsystem\/theme","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Theme","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Theme","kind":"identifier"}],"navigatorTitle":[{"text":"Theme","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem","url":"\/documentation\/glovounifieddesignsystem","type":"topic","title":"GlovoUnifiedDesignSystem","role":"collection","abstract":[]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/UIKit":{"url":"\/documentation\/glovounifieddesignsystem\/uikit","role":"collection","title":"UIKit","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/UIKit","type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/HelperTextStyle":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/HelperTextStyle","url":"\/documentation\/glovounifieddesignsystem\/helpertextstyle","navigatorTitle":[{"kind":"identifier","text":"HelperTextStyle"}],"type":"topic","title":"HelperTextStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelperTextStyle"}],"abstract":[{"type":"text","text":"An enum that define the different style for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/HelperText"},{"text":" component","type":"text"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/SwiftUI":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/SwiftUI","url":"\/documentation\/glovounifieddesignsystem\/swiftui","abstract":[],"title":"SwiftUI","role":"collection","type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Blob01":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob01","url":"\/documentation\/glovounifieddesignsystem\/blob01","type":"topic","title":"Blob01","role":"symbol","navigatorTitle":[{"text":"Blob01","kind":"identifier"}],"abstract":[{"type":"text","text":"A Blob shape for varient 1, to be used in SwiftUI"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Blob01","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/ButtonStyle":{"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"ButtonStyle"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ButtonStyle","kind":"symbol","abstract":[],"type":"topic","title":"ButtonStyle","url":"\/documentation\/glovounifieddesignsystem\/buttonstyle","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonStyle","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/ThemeManager":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ThemeManager","type":"topic","kind":"symbol","title":"ThemeManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeManager"}],"url":"\/documentation\/glovounifieddesignsystem\/thememanager","navigatorTitle":[{"text":"ThemeManager","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/TextStyle":{"url":"\/documentation\/glovounifieddesignsystem\/textstyle","role":"symbol","title":"TextStyle","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TextStyle","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextStyle"}],"navigatorTitle":[{"text":"TextStyle","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that define "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TextStyle"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"PTXO comes by default with a predefined set of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TextStyle","type":"reference"},{"type":"text","text":" represented in "},{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreTextStyles","type":"reference","isActive":true}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/ThemeProtocol":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ThemeProtocol","abstract":[{"text":"A protocol that defines the theme requirements","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ThemeProtocol","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeProtocol"}],"role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/themeprotocol","title":"ThemeProtocol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/MarketingIllustrationBlob":{"kind":"symbol","url":"\/documentation\/glovounifieddesignsystem\/marketingillustrationblob","abstract":[],"role":"symbol","title":"MarketingIllustrationBlob","navigatorTitle":[{"text":"MarketingIllustrationBlob","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MarketingIllustrationBlob","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingIllustrationBlob"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/ColorSchemeProtocol":{"role":"symbol","title":"ColorSchemeProtocol","navigatorTitle":[{"text":"ColorSchemeProtocol","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ColorSchemeProtocol","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/colorschemeprotocol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ColorSchemeProtocol","abstract":[{"type":"text","text":"A protocol that defines an abstraction for a set of colors which are provided by the Core Theme. "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=1640%3A85963&mode=design&t=UrcYFf7V32yWzYD0-1"}],"kind":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/InputState":{"title":"InputState","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputState","url":"\/documentation\/glovounifieddesignsystem\/inputstate","navigatorTitle":[{"text":"InputState","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputState"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreSpacer":{"url":"\/documentation\/glovounifieddesignsystem\/corespacer","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreSpacer","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CoreSpacer","kind":"identifier"}],"navigatorTitle":[{"text":"CoreSpacer","kind":"identifier"}],"kind":"symbol","title":"CoreSpacer","abstract":[{"text":"A struct that a group of different configuration values for spacers ","type":"text"},{"type":"reference","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=13396%3A2810&mode=design&t=6FaBdJ3Fh3yPpMNO-1","isActive":true}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/LoyaltySecondaryTagStyle":{"navigatorTitle":[{"text":"LoyaltySecondaryTagStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/LoyaltySecondaryTagStyle","kind":"symbol","title":"LoyaltySecondaryTagStyle","url":"\/documentation\/glovounifieddesignsystem\/loyaltysecondarytagstyle","type":"topic","abstract":[{"text":"A TagStyle concrete type for representing ","type":"text"},{"type":"codeVoice","code":"Loyalty Secondary"},{"type":"text","text":" tag style"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoyaltySecondaryTagStyle","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/GlovoUnifiedDesignSystemVersionNumber":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/GlovoUnifiedDesignSystemVersionNumber","kind":"symbol","url":"\/documentation\/glovounifieddesignsystem\/glovounifieddesignsystemversionnumber","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"GlovoUnifiedDesignSystemVersionNumber"}],"title":"GlovoUnifiedDesignSystemVersionNumber"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PromotionBlobIcon":{"type":"topic","title":"PromotionBlobIcon","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PromotionBlobIcon","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PromotionBlobIcon","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionBlobIcon","kind":"symbol","url":"\/documentation\/glovounifieddesignsystem\/promotionblobicon","abstract":[{"type":"text","text":"A type for "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon","isActive":true},{"type":"text","text":" component which defines the appearance for the component for promotion style usage."}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/TextStylesProtocol":{"abstract":[{"type":"text","text":"A protocol that defines the text styles that will be provided by PTXO"}],"navigatorTitle":[{"text":"TextStylesProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TextStylesProtocol","title":"TextStylesProtocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextStylesProtocol","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/textstylesprotocol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Blob02":{"url":"\/documentation\/glovounifieddesignsystem\/blob02","kind":"symbol","abstract":[{"text":"A Blob shape for varient 2, to be used in SwiftUI","type":"text"}],"title":"Blob02","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Blob02","kind":"identifier"}],"navigatorTitle":[{"text":"Blob02","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob02"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/MarketingBlobIcon":{"url":"\/documentation\/glovounifieddesignsystem\/marketingblobicon","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MarketingBlobIcon"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MarketingBlobIcon","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingBlobIcon","type":"topic","abstract":[{"type":"text","text":"A type for "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon","isActive":true},{"type":"text","text":" component which defines the appearance for the component for marketing style usage."}],"role":"symbol","title":"MarketingBlobIcon"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/SecondaryButtonStyle":{"abstract":[{"type":"text","text":"Suggested, less prominent actions or frequently used actions"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/SecondaryButtonStyle","url":"\/documentation\/glovounifieddesignsystem\/secondarybuttonstyle","title":"SecondaryButtonStyle","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecondaryButtonStyle"}],"role":"symbol","navigatorTitle":[{"text":"SecondaryButtonStyle","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/NeutralTagStyle":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralTagStyle","abstract":[{"text":"A TagStyle concrete type for representing ","type":"text"},{"code":"Neutral","type":"codeVoice"},{"type":"text","text":" tag style"}],"title":"NeutralTagStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeutralTagStyle"}],"url":"\/documentation\/glovounifieddesignsystem\/neutraltagstyle","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeutralTagStyle"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/IllustrationBlobType":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IllustrationBlobType","navigatorTitle":[{"text":"IllustrationBlobType","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IllustrationBlobType","kind":"identifier"}],"role":"symbol","title":"IllustrationBlobType","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/glovounifieddesignsystem\/illustrationblobtype"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/IconAsset":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IconAsset","navigatorTitle":[{"text":"IconAsset","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"IconAsset","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/iconasset","title":"IconAsset","role":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/BadgeDisplayingProtocol":{"navigatorTitle":[{"kind":"identifier","text":"BadgeDisplayingProtocol"}],"url":"\/documentation\/glovounifieddesignsystem\/badgedisplayingprotocol","type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/BadgeDisplayingProtocol","title":"BadgeDisplayingProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BadgeDisplayingProtocol"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Blob06":{"url":"\/documentation\/glovounifieddesignsystem\/blob06","kind":"symbol","abstract":[{"type":"text","text":"A Blob shape for varient 6, to be used in SwiftUI"}],"navigatorTitle":[{"text":"Blob06","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob06","role":"symbol","type":"topic","title":"Blob06","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Blob06","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreColorSchemeProtocol":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreColorSchemeProtocol","abstract":[{"type":"text","text":"A protocol that represent the core colors and provide it default implementation"}],"url":"\/documentation\/glovounifieddesignsystem\/corecolorschemeprotocol","title":"CoreColorSchemeProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoreColorSchemeProtocol"}],"kind":"symbol","navigatorTitle":[{"text":"CoreColorSchemeProtocol","kind":"identifier"}]},"https://www.figma.com/file/TuxClC4JIItgCYAZiafQBt/Unified-Design-System?type=design&node-id=269%3A747&mode=design&t=j7JyXEY9I4J9AoES-1":{"url":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=269%3A747&mode=design&t=j7JyXEY9I4J9AoES-1","title":"Figma link","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=269%3A747&mode=design&t=j7JyXEY9I4J9AoES-1","type":"link","titleInlineContent":[{"type":"text","text":"Figma link"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Blob03":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob03","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Blob03","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A Blob shape for varient 3, to be used in SwiftUI"}],"role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/blob03","kind":"symbol","title":"Blob03","navigatorTitle":[{"kind":"identifier","text":"Blob03"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/NeutralButtonStyle":{"abstract":[{"text":"Additional actions that are available on the screen after the primary and secondary","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralButtonStyle","title":"NeutralButtonStyle","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"NeutralButtonStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeutralButtonStyle"}],"url":"\/documentation\/glovounifieddesignsystem\/neutralbuttonstyle","role":"symbol","type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/BlobIconTypeProtocol":{"title":"BlobIconTypeProtocol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"BlobIconTypeProtocol","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BlobIconTypeProtocol"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/BlobIconTypeProtocol","url":"\/documentation\/glovounifieddesignsystem\/blobicontypeprotocol","abstract":[{"text":"A protocol  that represents the abstraction for the ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon","isActive":true},{"text":" type.","type":"text"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Shadow04":{"url":"\/documentation\/glovounifieddesignsystem\/shadow04","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Shadow04","kind":"identifier"}],"abstract":[{"type":"text","text":"A Shadow shape for varient 4, to be used in SwiftUI"}],"role":"symbol","kind":"symbol","title":"Shadow04","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow04","type":"topic","navigatorTitle":[{"text":"Shadow04","kind":"identifier"}]},"https://www.figma.com/file/TuxClC4JIItgCYAZiafQBt/Unified-Design-System?type=design&node-id=13396%3A2810&mode=design&t=6FaBdJ3Fh3yPpMNO-1":{"type":"link","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=13396%3A2810&mode=design&t=6FaBdJ3Fh3yPpMNO-1","url":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=13396%3A2810&mode=design&t=6FaBdJ3Fh3yPpMNO-1","titleInlineContent":[{"text":"Figma Link","type":"text"}],"title":"Figma Link"},"https://www.figma.com/file/TuxClC4JIItgCYAZiafQBt/Unified-Design-System?type=design&node-id=1640%3A85963&mode=design&t=UrcYFf7V32yWzYD0-1":{"url":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=1640%3A85963&mode=design&t=UrcYFf7V32yWzYD0-1","title":"Figma link","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=1640%3A85963&mode=design&t=UrcYFf7V32yWzYD0-1","type":"link","titleInlineContent":[{"type":"text","text":"Figma link"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Shadow01":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Shadow01","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/shadow01","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow01","abstract":[{"type":"text","text":"A Shadow shape for varient 1, to be used in SwiftUI"}],"title":"Shadow01","navigatorTitle":[{"kind":"identifier","text":"Shadow01"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/ControlAlignment":{"navigatorTitle":[{"text":"ControlAlignment","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ControlAlignment","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ControlAlignment","kind":"symbol","url":"\/documentation\/glovounifieddesignsystem\/controlalignment","title":"ControlAlignment"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/ClickableIcon":{"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/ClickableIcon","url":"\/documentation\/glovounifieddesignsystem\/clickableicon","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ClickableIcon"}],"title":"ClickableIcon","navigatorTitle":[{"kind":"identifier","text":"ClickableIcon"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/TransparentButtonStyle":{"role":"symbol","abstract":[],"url":"\/documentation\/glovounifieddesignsystem\/transparentbuttonstyle","type":"topic","title":"TransparentButtonStyle","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TransparentButtonStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TransparentButtonStyle"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/TransparentButtonStyle","kind":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PTXOLogger":{"abstract":[{"text":"A type that sends log events to the appropriate service.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXOLogger","url":"\/documentation\/glovounifieddesignsystem\/ptxologger","title":"PTXOLogger","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PTXOLogger"}],"navigatorTitle":[{"text":"PTXOLogger","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/IllustrationSize":{"kind":"symbol","title":"IllustrationSize","abstract":[{"type":"text","text":"The size of the illustration"},{"type":"text","text":" "},{"isActive":true,"identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=17859-132336&mode=design&t=8XdUJNM2N0s1PV77-0","type":"reference"}],"url":"\/documentation\/glovounifieddesignsystem\/illustrationsize","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"IllustrationSize","kind":"identifier"}],"navigatorTitle":[{"text":"IllustrationSize","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IllustrationSize","role":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/InputFooter":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/InputFooter","title":"InputFooter","url":"\/documentation\/glovounifieddesignsystem\/inputfooter","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputFooter"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InputFooter"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreBorderWidth":{"url":"\/documentation\/glovounifieddesignsystem\/coreborderwidth","title":"CoreBorderWidth","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreBorderWidth","kind":"symbol","abstract":[{"type":"text","text":"A struct that a group of different configuration values for border width "},{"type":"reference","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=6158%3A53887&mode=design&t=6FaBdJ3Fh3yPpMNO-1","isActive":true}],"navigatorTitle":[{"text":"CoreBorderWidth","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreBorderWidth"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/IllustrationBlob":{"role":"symbol","title":"IllustrationBlob","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IllustrationBlob"}],"url":"\/documentation\/glovounifieddesignsystem\/illustrationblob","type":"topic","abstract":[{"text":"Unified Design System  BlobIcon.","type":"text"},{"text":" ","type":"text"},{"identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?node-id=17854%3A102215&mode=dev","isActive":true,"type":"reference"}],"navigatorTitle":[{"kind":"identifier","text":"IllustrationBlob"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/IllustrationBlob"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/NeutralIllustrationBlob":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralIllustrationBlob","abstract":[],"title":"NeutralIllustrationBlob","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeutralIllustrationBlob"}],"url":"\/documentation\/glovounifieddesignsystem\/neutralillustrationblob","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"NeutralIllustrationBlob","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CriticalSecondaryTagStyle":{"navigatorTitle":[{"kind":"identifier","text":"CriticalSecondaryTagStyle"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalSecondaryTagStyle","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CriticalSecondaryTagStyle","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/criticalsecondarytagstyle","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Critical Secondary"},{"text":" tag style","type":"text"}],"role":"symbol","title":"CriticalSecondaryTagStyle","type":"topic","kind":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreTheme":{"type":"topic","abstract":[{"text":"A typealias that refer the a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Theme","isActive":true,"type":"reference"},{"type":"text","text":" object with specifying the generic requirements to the core theme’s data types"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreTheme","url":"\/documentation\/glovounifieddesignsystem\/coretheme","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreTheme","kind":"identifier"}],"title":"CoreTheme","navigatorTitle":[{"kind":"identifier","text":"CoreTheme"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/WarningSecondaryTagStyle":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/WarningSecondaryTagStyle","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Warning Secondary"},{"type":"text","text":" tag style"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"WarningSecondaryTagStyle"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WarningSecondaryTagStyle"}],"role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/warningsecondarytagstyle","title":"WarningSecondaryTagStyle"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/MarketingSecondaryTagStyle":{"navigatorTitle":[{"text":"MarketingSecondaryTagStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/MarketingSecondaryTagStyle","kind":"symbol","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Marketing Secondary"},{"text":" tag style","type":"text"}],"url":"\/documentation\/glovounifieddesignsystem\/marketingsecondarytagstyle","type":"topic","title":"MarketingSecondaryTagStyle","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MarketingSecondaryTagStyle","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CoreTextStylesProtocol":{"abstract":[{"text":"The CoreTheme’s set of predefined ","type":"text"},{"code":"TextStyle","type":"codeVoice"},{"text":" which are provided by PTXO.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Subclass this class in case you need to extend or modify the CoreTheme’s values in the Local Design system"},{"type":"text","text":" "},{"type":"reference","identifier":"https:\/\/www.figma.com\/file\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?type=design&node-id=269%3A747&mode=design&t=j7JyXEY9I4J9AoES-1","isActive":true}],"navigatorTitle":[{"text":"CoreTextStylesProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CoreTextStylesProtocol","title":"CoreTextStylesProtocol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CoreTextStylesProtocol","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/coretextstylesprotocol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/UDS":{"deprecated":true,"abstract":[{"type":"text","text":"A name space the will act as an umbrella for all the PTXO Atoms"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/UDS","title":"UDS","url":"\/documentation\/glovounifieddesignsystem\/uds","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"UDS","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UDS","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PTXO/HelperText":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/HelperText","url":"\/documentation\/glovounifieddesignsystem\/ptxo\/helpertext","navigatorTitle":[{"text":"HelperText","kind":"identifier"}],"type":"topic","title":"PTXO.HelperText","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelperText","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PTXO/Tag":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Tag"}],"navigatorTitle":[{"text":"Tag","kind":"identifier"}],"abstract":[{"text":"Unified Design System  Tag.","type":"text"},{"text":" ","type":"text"},{"identifier":"https:\/\/www.figma.com\/design\/TuxClC4JIItgCYAZiafQBt\/Unified-Design-System?m=auto&node-id=20606%3A18441&t=euwEJRAYWn4rD5Il-1","type":"reference","isActive":true}],"title":"PTXO.Tag","role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/ptxo\/tag","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/Tag","kind":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/EmptyStyle":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/EmptyStyle","abstract":[],"title":"EmptyStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmptyStyle"}],"url":"\/documentation\/glovounifieddesignsystem\/emptystyle","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmptyStyle"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CriticalBlobIcon":{"abstract":[{"type":"text","text":"A type for "},{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon","isActive":true,"type":"reference"},{"text":" component which defines the appearance for the component for critical style usage.","type":"text"}],"title":"CriticalBlobIcon","role":"symbol","navigatorTitle":[{"text":"CriticalBlobIcon","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/criticalblobicon","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalBlobIcon","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CriticalBlobIcon","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PositiveTagStyle":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveTagStyle","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Positive"},{"text":" tag style","type":"text"}],"title":"PositiveTagStyle","url":"\/documentation\/glovounifieddesignsystem\/positivetagstyle","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PositiveTagStyle","kind":"identifier"}],"navigatorTitle":[{"text":"PositiveTagStyle","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/NeutralBlobIcon":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/NeutralBlobIcon","url":"\/documentation\/glovounifieddesignsystem\/neutralblobicon","navigatorTitle":[{"kind":"identifier","text":"NeutralBlobIcon"}],"type":"topic","title":"NeutralBlobIcon","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeutralBlobIcon"}],"abstract":[{"type":"text","text":"A type for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon"},{"text":" component which defines the appearance for the component for neutral style  usage.","type":"text"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/FoundationUnitsProtocol":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/FoundationUnitsProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FoundationUnitsProtocol","kind":"identifier"}],"type":"topic","role":"symbol","title":"FoundationUnitsProtocol","navigatorTitle":[{"kind":"identifier","text":"FoundationUnitsProtocol"}],"abstract":[],"url":"\/documentation\/glovounifieddesignsystem\/foundationunitsprotocol","kind":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Shadow05":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Shadow05"}],"navigatorTitle":[{"text":"Shadow05","kind":"identifier"}],"abstract":[{"type":"text","text":"A Shadow shape for varient 5, to be used in SwiftUI"}],"title":"Shadow05","role":"symbol","url":"\/documentation\/glovounifieddesignsystem\/shadow05","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Shadow05"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CriticalIllustrationBlob":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalIllustrationBlob","abstract":[],"title":"CriticalIllustrationBlob","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CriticalIllustrationBlob"}],"url":"\/documentation\/glovounifieddesignsystem\/criticalillustrationblob","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CriticalIllustrationBlob","kind":"identifier"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/LoyaltyBlobIcon":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoyaltyBlobIcon","kind":"identifier"}],"url":"\/documentation\/glovounifieddesignsystem\/loyaltyblobicon","type":"topic","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/LoyaltyBlobIcon","abstract":[{"text":"A type for ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon","type":"reference","isActive":true},{"text":" component which defines the appearance for the component for promotion style usage.","type":"text"}],"title":"LoyaltyBlobIcon","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LoyaltyBlobIcon"}]},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PositiveBlobIcon":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PositiveBlobIcon","type":"topic","navigatorTitle":[{"text":"PositiveBlobIcon","kind":"identifier"}],"abstract":[{"type":"text","text":"A type for "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PTXO\/BlobIcon","isActive":true},{"type":"text","text":" component which defines the appearance for the component for positive style usage."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PositiveBlobIcon"}],"url":"\/documentation\/glovounifieddesignsystem\/positiveblobicon","kind":"symbol","title":"PositiveBlobIcon"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/PromotionSecondaryTagStyle":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/PromotionSecondaryTagStyle","abstract":[{"text":"A TagStyle concrete type for representing ","type":"text"},{"type":"codeVoice","code":"Promotion Secondary"},{"text":" tag style","type":"text"}],"title":"PromotionSecondaryTagStyle","url":"\/documentation\/glovounifieddesignsystem\/promotionsecondarytagstyle","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PromotionSecondaryTagStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PromotionSecondaryTagStyle"}],"type":"topic"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/GlovoUnifiedDesignSystemVersionString":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/GlovoUnifiedDesignSystemVersionString","title":"GlovoUnifiedDesignSystemVersionString","type":"topic","fragments":[{"kind":"identifier","text":"GlovoUnifiedDesignSystemVersionString"}],"url":"\/documentation\/glovounifieddesignsystem\/glovounifieddesignsystemversionstring","abstract":[],"role":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/CriticalButtonStyle":{"url":"\/documentation\/glovounifieddesignsystem\/criticalbuttonstyle","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CriticalButtonStyle"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/CriticalButtonStyle","type":"topic","abstract":[{"type":"text","text":"Actions that are destructive or not easily reversible"}],"role":"symbol","navigatorTitle":[{"text":"CriticalButtonStyle","kind":"identifier"}],"title":"CriticalButtonStyle"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Foundation":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Foundation","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/glovounifieddesignsystem\/foundation","title":"Foundation","role":"collection"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/Blob05":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Blob05","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A Blob shape for varient 5, to be used in SwiftUI","type":"text"}],"title":"Blob05","url":"\/documentation\/glovounifieddesignsystem\/blob05","navigatorTitle":[{"kind":"identifier","text":"Blob05"}],"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/Blob05","role":"symbol"},"doc://org.cocoapods.GlovoUnifiedDesignSystem/documentation/GlovoUnifiedDesignSystem/WarningTagStyle":{"identifier":"doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/WarningTagStyle","navigatorTitle":[{"kind":"identifier","text":"WarningTagStyle"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WarningTagStyle"}],"title":"WarningTagStyle","role":"symbol","type":"topic","url":"\/documentation\/glovounifieddesignsystem\/warningtagstyle","abstract":[{"type":"text","text":"A TagStyle concrete type for representing "},{"type":"codeVoice","code":"Warning"},{"type":"text","text":" tag style"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/GlovoUnifiedDesignSystemVersionNumber","doc:\/\/org.cocoapods.GlovoUnifiedDesignSystem\/documentation\/GlovoUnifiedDesignSystem\/GlovoUnifiedDesignSystemVersionString"],"title":"Variables"}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}